import Head from "next/head";
import styles from "../styles/Home.module.css";
import React from "react";

export default function Home() {
	const [state, setState] = React.useState({});
	const url = process.env.REACT_APP_ALB_ADDRESS;
	console.log(url);
	React.useEffect(() => {
		const callAPI = async () => {
			try {
				console.log(
					"http://hieunm-production-lb-2118528627.ap-southeast-1.elb.amazonaws.com:8080"
				);
				const res = await fetch(url);
				const data = await res.json();
				console.log(data);

				setState(data);
			} catch (err) {
				console.log(err);
			}
		};

		callAPI();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<h1>Message from server:{state?.message}</h1>
			</div>
		</div>
	);
}
